import { esc } from "./shared.js?v=1.5.0";

/** Shared workspace primitives. Page-specific CSS should only define its layout. */
export const pageHeader = (title, description, actions = "") =>
  `<header class="page-header"><div class="page-heading"><h1>${esc(title)}</h1><p>${esc(description)}</p></div><div class="page-actions">${actions}</div></header>`;
export const workspaceCSS = `
:host{--ab-radius:12px;--ab-control-radius:8px;--ab-space:24px;--ab-danger:#b34135;--ab-danger-bg:#fff0eb;--ab-accent-solid:#21634d;--ab-surface-alt:color-mix(in srgb,var(--ab-surface) 94%,var(--ab-text));--ab-focus:#4c9e80;font-size:14px;line-height:1.5}
:host([data-dark]){--ab-danger:#f6aaa0;--ab-danger-bg:#452826;--ab-accent-solid:#28694f;--ab-focus:#9bddbf}
main,.shell{width:100%;max-width:1440px;margin:0 auto;padding:28px 32px 48px;min-width:0}
main.view{padding:0;max-width:none}
.page-header{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin:0 0 28px;padding:0}
.page-heading{min-width:0}.page-heading h1{font-size:28px;line-height:1.2;letter-spacing:-.7px;font-weight:650;margin:0}.page-heading p{color:var(--ab-muted);font-size:14px;line-height:1.55;margin:8px 0 0;max-width:650px}
.page-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap;justify-content:flex-end;flex-shrink:0}
h2{font-size:17px;font-weight:650;line-height:1.4;letter-spacing:-.2px}h3{font-size:14px;font-weight:600;line-height:1.4}p{line-height:1.6}
button{min-height:40px;padding:9px 13px;font-size:13px;line-height:1.4;border-radius:var(--ab-control-radius);font-weight:600;transition:background .12s,border-color .12s;color:var(--ab-text)}button.primary{background:var(--ab-accent-solid);border-color:var(--ab-accent-solid);color:white}button.quiet{background:transparent;border-color:transparent;color:var(--ab-muted)}button:disabled{cursor:default;opacity:.45}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible,a:focus-visible{outline:2px solid var(--ab-focus);outline-offset:3px}button.icon{min-width:40px;padding:9px}ha-icon{--mdc-icon-size:20px;flex-shrink:0}
.box,.stat{border-radius:var(--ab-radius);border:1px solid var(--ab-line);background:var(--ab-surface);box-shadow:0 1px 2px #00000003}.box-head{padding:20px 22px}.box h2+p,.box h3+p{margin-top:5px;color:var(--ab-muted)}.grid{gap:16px}.toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:0 0 20px}.toolbar h2{margin-right:auto}.box>.toolbar:last-child{margin-bottom:0}.metric,.stat .value{font-size:28px;font-weight:650;line-height:1.3;letter-spacing:-.6px;font-variant-numeric:tabular-nums;overflow-wrap:anywhere;margin:10px 0}.number,.numbers,.amount,.reserve-total{font-variant-numeric:tabular-nums}.small,small{font-size:12px}.muted{color:var(--ab-muted)}.positive{color:var(--ab-green)}.negative{color:var(--ab-danger)}
.badge,.status-pill{display:inline-flex;align-items:center;gap:5px;width:fit-content;font-size:11px;font-weight:600;padding:3px 8px;border-radius:6px;line-height:1.5;background:var(--ab-surface-alt);color:var(--ab-muted)}.status-pill.cleared,.status-pill.reconciled{background:var(--ab-pale);color:var(--ab-green)}.status-pill.pending{background:var(--ab-danger-bg);color:var(--ab-danger)}
.table,.table-wrap{max-width:100%;overflow:auto;overscroll-behavior-x:contain}table{width:100%;border-collapse:collapse;font-size:13px}th{font-size:11px;letter-spacing:.45px;text-transform:uppercase;font-weight:600;color:var(--ab-muted);background:var(--ab-surface-alt);padding:12px 16px}td{padding:14px 16px;border-bottom:1px solid var(--ab-line);font-size:13px}tbody tr:last-child td{border-bottom:0}tbody tr:hover{background:color-mix(in srgb,var(--ab-pale) 35%,transparent)}td.numbers,th.numbers{text-align:right;white-space:nowrap}.box.table{padding:0}.box.table>h2{padding:20px 22px}.box.table>.toolbar{padding:14px 20px;margin:0;border-top:1px solid var(--ab-line)}
input:not([type=checkbox]):not([type=radio]),select,textarea,.field input,.field select{width:100%;min-width:0;min-height:42px;padding:10px 12px;border:1px solid var(--ab-line);border-radius:var(--ab-control-radius);font:inherit;font-size:14px;color:var(--ab-text);background:var(--ab-surface);box-sizing:border-box}input[type=checkbox],input[type=radio]{width:18px;height:18px;min-height:18px;padding:0;accent-color:var(--ab-accent-solid);flex:none}label,.field{font-size:13px;font-weight:500;gap:7px}.row:has(>input[type=checkbox]),.checkbox{display:flex;align-items:flex-start;gap:10px;font-weight:400}.row:has(>input[type=checkbox]) input{margin-top:2px}.field small{font-size:12px}
.dialog{padding:0;width:min(680px,calc(100% - 32px));max-width:680px;max-height:92dvh;border:1px solid var(--ab-line);border-radius:16px;background:var(--ab-surface);color:var(--ab-text);box-shadow:0 24px 100px #0005;overflow:auto;overscroll-behavior:contain}.dialog:not([open]),[hidden]{display:none!important}.dialog::backdrop{background:#12241ec0;backdrop-filter:blur(3px)}.dialog header{padding:20px 24px;display:flex;align-items:center;justify-content:space-between;gap:16px;border-bottom:1px solid var(--ab-line);position:sticky;top:0;z-index:2;background:var(--ab-surface)}.dialog header h2{margin:0;font-size:19px}.dialog header button{margin:-4px -8px -4px 0}.dialog form,.dialog .dialog-content{padding:24px}.dialog .form,.dialog .form-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.dialog footer,.dialog-actions{display:flex;align-items:center;justify-content:flex-end;gap:10px;margin:24px -24px -24px;padding:16px 24px;background:var(--ab-surface);border-top:1px solid var(--ab-line);position:sticky;bottom:0;z-index:1}.dialog footer button,.dialog-actions button{min-width:96px}.dialog footer button.quiet,.dialog-actions button.icon{min-width:40px}.full{grid-column:1/-1}.form-section{grid-column:1/-1;border:0;border-top:1px solid var(--ab-line);padding:20px 0 0;margin:4px 0 0;min-width:0;display:grid;grid-template-columns:1fr 1fr;gap:18px}.form-section legend{font-size:13px;font-weight:650;padding:0 8px 0 0}.advanced{grid-column:1/-1;margin:0;padding:16px;border:1px solid var(--ab-line);border-radius:var(--ab-control-radius);background:var(--ab-surface-alt)}.advanced summary{cursor:pointer;font-weight:600}.advanced[open] summary{margin-bottom:16px}.advanced .form-section{border:0;padding:0}.dialog .form-error,.dialog .error{margin:16px 0 0}.error,.form-error{color:var(--ab-danger);background:var(--ab-danger-bg);border-radius:8px;padding:12px 14px;font-size:13px;overflow-wrap:anywhere}.error:empty,.form-error:empty{display:none}.notice,.help{background:var(--ab-pale);color:var(--ab-text);border-radius:8px;padding:14px 16px;font-size:13px}.empty{padding:40px 24px;color:var(--ab-muted)}.empty h2,.empty h3{color:var(--ab-text);margin-bottom:8px}.empty p{margin:8px auto 20px;max-width:460px}.empty svg{color:var(--ab-green)}.toast{border-radius:8px;font-size:13px}.section-heading{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:24px 0 12px}.section-heading:first-child{margin-top:0}.section-heading h2{font-size:14px}.section-heading .count{margin-left:8px;font-size:12px;color:var(--ab-muted);font-weight:400}
@media(max-width:1050px){main,.shell{padding:24px}.page-header{gap:16px}.page-heading h1{font-size:25px}.page-actions{max-width:48%}}
@media(max-width:650px){main,.shell{padding:20px 14px 32px}.page-header{display:block;margin-bottom:22px}.page-heading h1{font-size:24px}.page-heading p{font-size:13px;margin-top:6px}.page-actions{margin-top:16px;max-width:none;justify-content:flex-start}.page-actions .primary{margin-left:0}.page-actions{gap:6px}.page-actions button{padding:9px 10px}button{min-height:44px}.metric,.stat .value{font-size:25px}.dialog{width:calc(100% - 16px);max-height:94dvh;border-radius:14px}.dialog header{padding:16px 20px}.dialog form,.dialog .dialog-content{padding:20px}.dialog .form,.dialog .form-grid,.form-section{grid-template-columns:1fr}.dialog footer,.dialog-actions{margin:20px -20px -20px;padding:14px 20px}.full{grid-column:1/-1}.grid{grid-template-columns:1fr}.toolbar{gap:8px}.box-head{padding:18px}.box.table>h2{padding:18px}.splits{grid-template-columns:1fr 1fr}th,td{padding:12px}.status-pill{font-size:11px}.section-heading{margin-top:22px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
@media print{:host,:host([data-dark]){--ab-bg:white;--ab-surface:white;--ab-text:#182d24;--ab-muted:#56665f;--ab-line:#dce3df;--ab-pale:#eef4f0;--ab-surface-alt:#f3f5f4;background:white;color:var(--ab-text)}.page-actions,.toolbar,button,.dialog{display:none!important}main,.shell{padding:0;max-width:none}.box,.stat{break-inside:avoid;box-shadow:none}.table{overflow:visible}.page-heading h1{font-size:22px}}
`;

/** Dashboard cards use the same type scale and borders, respecting HA card themes. */
export const cardCSS = `ha-card{border-radius:var(--ha-card-border-radius,12px);border:1px solid var(--ab-line);background:var(--ha-card-background,var(--ab-surface));padding:22px;box-shadow:var(--ha-card-box-shadow,none)}h2{font-size:17px;line-height:1.4;font-weight:650}.value{font-variant-numeric:tabular-nums;letter-spacing:-.5px;line-height:1.3}.label,.small,header .muted{font-size:12px;line-height:1.5}.metrics{gap:16px}a{font-size:13px;min-height:40px;align-items:center}a:focus-visible{outline:2px solid var(--ab-green);outline-offset:4px}@media(max-width:450px){ha-card{padding:18px}}`;
